# NOTE: Generated By HttpRunner v3.1.4
# FROM: jc.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseJc(HttpRunner):

    config = Config("jc").base_url("http://127.0.0.1:5000")

    teststeps = [
        Step(
            RunRequest("haha")
            .get("/haha")
            .validate()
            .assert_equal("body.name", "jc")
            .assert_equal("body.age", 99)
            .assert_equal("body.addr", "hangzhou")
        ),
    ]


if __name__ == "__main__":
    TestCaseJc().test_start()
