# NOTE: Generated By HttpRunner v3.1.4
# FROM: PycharmProjects\zixueday1\study\httprunners\login1.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin1(HttpRunner):

    config = Config("jiekouceshi").base_url("http://127.0.0.1:5000")

    teststeps = [
        Step(
            RunRequest("测试login接口1")
            .get("/login")
            .with_params(**{"name": "jiangchen", "pwd": "123456"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.name", "jiangchen")
            .assert_equal("body.pwd", "123456")
        ),
        Step(
            RunRequest("test233433")
            .get("/login")
            .with_params(**{"name": "jiangchen", "pwd": "123"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.name", "jiangchen")
            .assert_equal("body.pwd", "123")
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin1().test_start()
